version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gym_backend_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: gym_management
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - container_network_1

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - container_network_1

networks:
      - container_network_1

volumes:
  postgres_data: